# Generated by Django 6.0.4 on 2026-04-09 18:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('categoria', models.CharField(choices=[('BURACO', 'Buraco'), ('LIXO', 'Lixo'), ('ILUMINACAO', 'Iluminacao'), ('OUTRO', 'Outro')], max_length=20)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('rua', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('PROBLEMA', 'Problema'), ('PENDENTE', 'Pendente'), ('RESOLVIDO', 'Resolvido')], default='PROBLEMA', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='fixcity.chamado')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['criado_em'],
            },
        ),
    ]
